# Generated by Django 5.2.7 on 2025-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_account_blocked_until_user_account_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fail_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
