# Generated by Django 5.2.7 on 2025-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_fail_login_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_blocked_until',
            new_name='account_locked_until',
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
