# Generated by Django 5.2.7 on 2025-10-27 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_rename_account_blocked_until_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('FAILED_LOGIN', 'Failed Login Attempt')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField(null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
    ]
