# Generated by Django 5.2.7 on 2025-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
