# Generated by Django 5.2.7 on 2025-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_auditlog_user_ip_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
